---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-gitlab
      gitlab_letsencrypt: no
      gitlab_cleanup_ruby: no
      gitlab_trusted_certs:
        - isrgrootx1.pem  # A root certificate for letsencrypt.
