---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check gitlab-runsvdir service
      ansible.builtin.service:
        name: gitlab-runsvdir
      check_mode: true
      register: gitlab_service_check
      failed_when:
        - gitlab_service_check is changed

    - name: Check gitlab status
      ansible.builtin.command:
        cmd: gitlab-ctl status
      changed_when: false

    - name: See if web interface can be used
      ansible.builtin.uri:
        url: "http://localhost/users/sign_in"
